spring.application.name=config-prod
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.mvc.enabled=false
eureka.client.service-url.defaultZone= http://localhost:8085/eureka
